version: 2
updates:
    # Enable version updates for pip dependencies
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
          day: friday
      open-pull-requests-limit: 10
      labels:
          - "dependencies"
          - "python"
      commit-message:
          prefix: "deps"
          include: "scope"
      groups:
          python-dependencies:
              patterns:
                  - "*"

    # Enable version updates for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "friday"
      open-pull-requests-limit: 5
      labels:
          - "dependencies"
          - "github-actions"
      commit-message:
          prefix: "ci"
          include: "scope"
      groups:
          github-actions:
              patterns:
                  - "*"
