services:
  atomic-red-team-mcp-server:
    build: .
    container_name: atomic-red-team-mcp-server
    ports:
      - "2786:8000"
    environment:
      - MCP_TRANSPORT=streamable-http
      - MCP_PORT=8000
      # Uncomment to enable static token authentication
      # - MCP_AUTH_TOKEN=your-secure-token-here
      # - MCP_AUTH_CLIENT_ID=authorized-client
      # - MCP_AUTH_SCOPES=read,admin
    stdin_open: true
    tty: true
    restart: unless-stopped
