name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  bump-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install bump-my-version
      run: uv tool install bump-my-version

    - name: Get current version
      id: current_version
      run: |
        CURRENT_VERSION=$(uv tool run bump-my-version show current_version)
        echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION"

    - name: Bump version
      id: bump_version
      run: |
        echo "Bumping ${{ github.event.inputs.version_bump }} version..."
        uv tool run bump-my-version bump ${{ github.event.inputs.version_bump }}

        NEW_VERSION=$(uv tool run bump-my-version show current_version)
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "New version: $NEW_VERSION"

    - name: Push changes
      run: |
        git push origin main
        git push origin v${{ steps.bump_version.outputs.version }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.bump_version.outputs.version }}
        name: Release v${{ steps.bump_version.outputs.version }}
        body: |
          ## Changes in v${{ steps.bump_version.outputs.version }}

          Version bumped from ${{ steps.current_version.outputs.version }} to ${{ steps.bump_version.outputs.version }} (${{ github.event.inputs.version_bump }} release)

          ### What's Changed
          See the [commit history](https://github.com/${{ github.repository }}/compare/v${{ steps.current_version.outputs.version }}...v${{ steps.bump_version.outputs.version }}) for details.

          ### Installation

          **Using uvx (recommended):**
          \`\`\`bash
          uvx atomic-red-team-mcp@${{ steps.bump_version.outputs.version }}
          \`\`\`

          **Using Docker:**
          \`\`\`bash
          docker run --rm -i ghcr.io/cyberbuff/atomic-red-team-mcp:${{ steps.bump_version.outputs.version }}
          \`\`\`

          **From PyPI:**
          \`\`\`bash
          pip install atomic-red-team-mcp==${{ steps.bump_version.outputs.version }}
          \`\`\`
        generate_release_notes: true
        draft: false
        prerelease: false
